import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import useSWR from "swr";

const fetcher = (key: any) => fetch(key).then((res) => res.json());

function Users() {
  const { data } = useSWR("/api/users", fetcher);

  return (
    <ul>
      {data?.users?.map((user: any) => (
        <li key={user.id}>{user.name}</li>
      ))}
    </ul>
  );
}

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>User data from Serverless Cloud</h1>
        <Users />
      </main>
    </div>
  );
};

export default Home;
