import type {GetStaticProps, NextPage} from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import useSWR from "swr";
import {Character, GetCharacterResults} from "../types";
import Image from "next/image";
import imageLoader from "../imageLoader";
import Link from "next/link";

const fetcher = (key: any) => fetch(key).then((res) => res.json());

function Users() {
  const { data } = useSWR("/api/users", fetcher);

  return (
    <ul>
      {data?.users?.map((user: any) => (
        <li key={user.id}>{user.name}</li>
      ))}
    </ul>
  );
}

const Home: NextPage<{characters: Character[]}> = ({characters}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>User data from Serverless Cloud</h1>
        <Users />
          {
              characters.map(character=>
                  <div key={character.id}>
                      <Link href={`characters/${character.id}`}>
                          <a>
                              <h3>{character.name}</h3>
                          </a>
                      </Link>
                      <Image
                          loader={imageLoader}
                          unoptimized
                          src={character.image}
                          alt={character.name}
                          width={200}
                          height={200}
                      />
                  </div>
              )
          }
      </main>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async() => {
    const res = await fetch("https://rickandmortyapi.com/api/character")
    const { results }: GetCharacterResults = await res.json()
    return {
        props:{
            characters: results
        }
    }
}

export default Home;
